version: '3'
services:
  database:
    image: dbpg:v1
    build:
      context: ./pg
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: 'localhost'
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1234'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: thajeztah/pgadmin4
    ports:
      - "5050:5050"
    environment:
      PGADMIN_DEFAULT_EMAIL: 'rub21@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: '1234'